import { RecommendationsList } from "@/components/recommendations-list";
import { PageContainer } from "@/components/shell/page-container";
import { PageHeader } from "@/components/page-header";
import { clientRecommendations, DEMO_CLIENT_ID, getProperty } from "@/lib/data/store";

export const metadata = { title: "Recommendations" };

export default function RecommendationsPage() {
  const items = clientRecommendations
    .filter((r) => r.clientId === DEMO_CLIENT_ID)
    .map((r) => ({ ...r, propertyName: r.propertyId ? getProperty(r.propertyId)?.name : undefined }));
  return (
    <PageContainer>
      <PageHeader eyebrow="Proactive" title="Recommendations" subtitle="Generated by the recommendations agent from your holdings, policy limits and live market data." />
      <RecommendationsList items={items} />
    </PageContainer>
  );
}
