// Static copy of the agent catalogue (lib/ai/usage.ts agentCatalogue), for the public landing page.
// The registry is server-only; keep this list in step with it.
export const AGENTS: { name: string; label: string; group: string; description: string }[] = [
  { name: "research", label: "Research", group: "Mandate", description: "Market, asset, developer, comparables and regulatory dossier with citations." },
  { name: "underwriting", label: "Underwriting", group: "Mandate", description: "Sets assumptions; the financial engine computes IRR, NPV and Monte Carlo scenarios." },
  { name: "due-diligence", label: "Due diligence", group: "Mandate", description: "Severity-rated findings across title, escrow, developer, SPA, tax and valuation." },
  { name: "debate", label: "Debate", group: "Mandate", description: "Bull and bear cases argued in parallel, decided by a judge." },
  { name: "memo", label: "Memo", group: "Mandate", description: "Client-ready Allocation or Exit Memo in semantic HTML with key metrics." },
  { name: "portfolio-monitor", label: "Portfolio monitor", group: "Mandate", description: "Daily scan of holdings; raises severity-rated alerts." },
  { name: "developer-risk", label: "Developer risk", group: "Mandate", description: "Weekly score on delivery, financial health, litigation, sentiment and escrow." },
  { name: "comparables", label: "Comparables", group: "Mandate", description: "Ten nearest projects by pgvector similarity, plus weighted comparable transactions." },
  { name: "market-timing", label: "Market timing", group: "Mandate", description: "BUY, HOLD or SELL signal per emirate from twelve months of market data." },
  { name: "cross-border", label: "Cross-border", group: "Mandate", description: "UAE versus India return arbitrage, FEMA, repatriation, tax and succession." },
  { name: "recommender", label: "Recommender", group: "Mandate", description: "Next-best actions: exit windows, rebalancing and new opportunities." },
  { name: "valuation", label: "Valuation", group: "Mandate", description: "DCF, capitalisation rate, direct comparison and a Monte Carlo range, reconciled to one value." },
  { name: "nl-query", label: "Natural-language query", group: "Mandate", description: "Answers questions over the firm's data with streamed, cited responses." },
  { name: "maharera-compliance", label: "MahaRERA compliance", group: "India", description: "Checks a Mumbai project against MahaRERA, IGR, Ready Reckoner, land records, MCGM approvals and society records." },
  { name: "goa-land-use", label: "Goa land use", group: "India", description: "RP 2021 zoning, conversion, CRZ, Comunidade, mundkar and title chain for a Goa property, with buyer eligibility." },
  { name: "india-tax-advisor", label: "India tax advisor", group: "India", description: "Explains stamp duty, registration, GST, TDS and capital gains from the rules engine, with lawful structuring and filings." },
  { name: "nri-workflow", label: "NRI workflow", group: "India", description: "Step-by-step purchase or sale plan for an NRI client from the UAE: accounts, power of attorney, payments, registration, TDS and repatriation." },
  { name: "ready-reckoner", label: "Ready Reckoner", group: "India", description: "Compares the agreement value with the Ready Reckoner value and registered comparables; stamp duty base and s.50C exposure." },
  { name: "deal-predictor", label: "Deal predictor", group: "Deals", description: "Win probability and expected days to close, from stage, offers, checklist and the firm's own closing record." },
  { name: "offer-strategist", label: "Offer strategist", group: "Deals", description: "Opening offer, target and walk-away prices with terms to trade, from comparables, valuation and the counterparty's position." },
  { name: "negotiation-coach", label: "Negotiation coach", group: "Deals", description: "Reads the concession pattern and recommends the next move with a script." },
  { name: "contract-reviewer", label: "Contract reviewer", group: "Deals", description: "Reviews a contract against the accepted terms and the jurisdiction's requirements; issues by severity with amendments." },
  { name: "closing-coordinator", label: "Closing coordinator", group: "Deals", description: "Critical path to completion, items at risk and the next three actions with owners." },
  { name: "payment-reminder", label: "Payment reminder", group: "Deals", description: "Drafts reminders for milestones due within seven days or overdue, with tone matched to the delay." },
  { name: "commission-computer", label: "Commission computer", group: "Commission", description: "Verifies the engine's commission and splits against the structure, the arithmetic and the firm's history, and explains them for sign-off." },
  { name: "anomaly-detector", label: "Anomaly detector", group: "Commission", description: "Flags commissions out of line with the firm's history, structure or market norms." },
  { name: "tax-advisor", label: "Tax advisor", group: "Commission", description: "VAT, GST and s.194H TDS treatment of a commission invoice, with the returns and deadlines it feeds." },
  { name: "collection-agent", label: "Collection agent", group: "Commission", description: "Receivables aging, expected collections and the next chase for each invoice, with drafted messages." },
  { name: "kyc-analyzer", label: "KYC analyzer", group: "Clients", description: "Reads the KYC file and screening results; readiness, risk rating, missing and expiring documents." },
  { name: "aml-screener", label: "AML screener", group: "Clients", description: "Dispositions sanctions, PEP and adverse media alerts and decides on enhanced due diligence." },
  { name: "report-writer", label: "Report writer", group: "Clients", description: "Writes quarterly and annual client reports in the firm's house style from the portfolio, goals and transactions." },
  { name: "statement-generator", label: "Statement generator", group: "Clients", description: "Commentary and highlights for the monthly client statement." },
  { name: "client-success-agent", label: "Client success", group: "Clients", description: "Relationship health score, churn risk and the next best actions with owners and dates." },
  { name: "goal-tracker", label: "Goal tracker", group: "Clients", description: "Classifies each client goal as on track or behind and proposes adjustments." },
  { name: "private-banking-coordinator", label: "Private banking coordinator", group: "Clients", description: "For clients above AED 50M: lending, structuring, succession and concierge to coordinate with partner institutions." },
  { name: "benchmark-computer", label: "Benchmark computer", group: "Intelligence", description: "Reviews each benchmark run: publishable and suppressed benchmarks, notable figures and data quality." },
  { name: "firm-analyst", label: "Firm analyst", group: "Intelligence", description: "Reads the firm's operating metrics against the anonymised cohort: strengths, gaps and priorities." },
  { name: "market-report-writer", label: "Market report writer", group: "Intelligence", description: "Writes the monthly market pulse for one market from twelve months of data." },
  { name: "data-product-packager", label: "Data product packager", group: "Intelligence", description: "Packages each issue of a data product from published data only, with quality checks and release notes." },
  { name: "quarterly-outlook-generator", label: "Quarterly outlook", group: "Intelligence", description: "The committee's quarterly outlook for one market: stance, case, scenarios and what would change the view." },
  { name: "automation-builder", label: "Automation builder", group: "Platform", description: "Turns a plain-English request into a trigger, conditions and actions." },
  { name: "notification-router", label: "Notification router", group: "Platform", description: "Decides who needs to know about an event and by which channel, honouring preferences." },
  { name: "permission-suggester", label: "Permission suggester", group: "Platform", description: "Suggests the least-privilege access role from what a user actually does." },
  { name: "audit-narrator", label: "Audit narrator", group: "Platform", description: "Turns an audit trail into a dated account with key events and anomalies." },
  { name: "data-quality-agent", label: "Data quality", group: "Platform", description: "Scores the workspace's data quality and orders the fixes by risk." },
];
