import type { DB } from "@/db";
import * as s from "@/db/schema";
import type { DcprFacts, MumbaiApprovals, TitleEvent } from "@/db/schema";
import { embed } from "@/lib/ai/embed";
import { parseLandRecord, type LandRecordKind } from "@/lib/india/parsers";
import { READY_RECKONER, READY_RECKONER_YEAR, GOA_MINIMUM_VALUE } from "@/lib/india/ready-reckoner";
import { sample712, sampleComunidade, sampleFormI, samplePropertyCard } from "@/lib/india/samples";
import { PROPERTIES } from "./seed-data";

/**
 * India records for the Mumbai and Goa projects: RERA registration, Ready
 * Reckoner zone, CTS and survey numbers, society and MCGM approvals, DCPR
 * facts, Goa land use, CRZ, Comunidade and mundkar status, RERA complaints
 * against the developers, and sample land records parsed by the same
 * parsers used for uploads. Synthetic; deterministic ids keep it idempotent.
 */

type Mumbai = { village: string; cts: string; rrZone: string; society?: string; noc?: "pending" | "issued" | "refused" | "not_applicable"; scheme?: "MHADA" | "SRA" | "33(7)" | "33(9)"; dcpr: DcprFacts; approvals: MumbaiApprovals; rera: "registered" | "extended" | "completed" | "lapsed"; validUntil: string; carpet: number };
type Goa = { taluka: string; village: string; survey: string; sub: string; landUse: "settlement" | "orchard" | "commercial"; rp: string; crz: "none" | "CRZ-II" | "CRZ-III"; comunidade?: string; mundkar: "none" | "claimed" | "declared" | "settled"; conversion: "not_required" | "sanad_obtained" | "applied" | "required"; conversionDays?: number; rera: "registered" | "extended" | "completed" | "lapsed"; validUntil: string; carpet: number; history: TitleEvent[] };

const ok = (y: number): MumbaiApprovals => ({ iod: `CE/${y - 4}/WS/AK`, cc: `CE/${y - 3}/WS/AK/CC`, oc: `CE/${y}/WS/AK/OCC`, fireNoc: `FB/HR/${y - 1}` });
const uc = (y: number): MumbaiApprovals => ({ iod: `CE/${y}/WS/AK`, cc: `CE/${y + 1}/WS/AK/CC`, oc: null, fireNoc: `FB/HR/${y + 1}` });

export const MUMBAI: Record<string, Mumbai> = {
  "rustomjee-elements": { village: "Juhu", cts: "1123/A", rrZone: "Andheri West 33/148", society: "Rustomjee Elements CHS Ltd", noc: "issued", dcpr: { zone: "Suburbs", plotAreaSqm: 21_400, roadWidthM: 18, fsiConsumed: 2.42, premiumFsi: 0.5, tdrLoaded: 0.4 }, approvals: ok(2022), rera: "completed", validUntil: "2022-12-31", carpet: 92 },
  "oberoi-sky-city": { village: "Magathane", cts: "212/1", rrZone: "Borivali East 51/239", society: "Sky City CHS Ltd", noc: "pending", dcpr: { zone: "Suburbs", plotAreaSqm: 101_000, roadWidthM: 30, fsiConsumed: 2.31, premiumFsi: 0.5, tdrLoaded: 0.35 }, approvals: ok(2024), rera: "completed", validUntil: "2024-06-30", carpet: 78 },
  "lodha-world-one": { village: "Lower Parel Division", cts: "1/1513", rrZone: "Worli 7/34", society: "World One CHS Ltd", noc: "issued", dcpr: { zone: "Island City", plotAreaSqm: 28_300, roadWidthM: 27, fsiConsumed: 3.48, premiumFsi: 0.5, tdrLoaded: 0 }, approvals: ok(2020), rera: "completed", validUntil: "2020-12-31", carpet: 210 },
  "lodha-park": { village: "Lower Parel Division", cts: "1/464", rrZone: "Lower Parel 5/22", society: "Lodha Park Federation", noc: "issued", dcpr: { zone: "Island City", plotAreaSqm: 70_800, roadWidthM: 24, fsiConsumed: 2.95, premiumFsi: 0.5, tdrLoaded: 0 }, approvals: ok(2021), rera: "completed", validUntil: "2021-12-31", carpet: 124 },
  "lodha-malabar": { village: "Malabar Hill Division", cts: "3/582", rrZone: "Malabar Hill 3/11", scheme: "33(7)", noc: "not_applicable", dcpr: { zone: "Island City", plotAreaSqm: 3_900, roadWidthM: 18, fsiConsumed: 3.0, premiumFsi: 0.5, tdrLoaded: 0 }, approvals: uc(2023), rera: "registered", validUntil: "2028-06-30", carpet: 380 },
  "oberoi-360-west": { village: "Worli Division", cts: "2/1561", rrZone: "Worli 7/34", society: "Three Sixty West CHS Ltd", noc: "issued", dcpr: { zone: "Island City", plotAreaSqm: 11_100, roadWidthM: 30, fsiConsumed: 3.85, premiumFsi: 0.5, tdrLoaded: 0 }, approvals: ok(2023), rera: "completed", validUntil: "2023-09-30", carpet: 470 },
  "oberoi-esquire": { village: "Pahadi Goregaon", cts: "15/2A", rrZone: "Goregaon East 41/192", society: "Esquire CHS Ltd", noc: "issued", dcpr: { zone: "Suburbs", plotAreaSqm: 34_500, roadWidthM: 30, fsiConsumed: 2.5, premiumFsi: 0.5, tdrLoaded: 0.4 }, approvals: ok(2019), rera: "completed", validUntil: "2019-12-31", carpet: 112 },
  "oberoi-enigma": { village: "Mulund", cts: "648/1", rrZone: "Mulund West 128/598", society: "Enigma CHS Ltd", noc: "issued", dcpr: { zone: "Suburbs", plotAreaSqm: 41_000, roadWidthM: 24, fsiConsumed: 2.22, premiumFsi: 0.5, tdrLoaded: 0.3 }, approvals: ok(2022), rera: "completed", validUntil: "2022-09-30", carpet: 118 },
  "rustomjee-crown": { village: "Lower Parel Division", cts: "1/1083", rrZone: "Prabhadevi 7/29", scheme: "33(9)", society: "Rustomjee Crown CHS Ltd", noc: "issued", dcpr: { zone: "Island City", plotAreaSqm: 19_600, roadWidthM: 18, fsiConsumed: 3.92, premiumFsi: 0.5, tdrLoaded: 0 }, approvals: ok(2024), rera: "completed", validUntil: "2024-03-31", carpet: 165 },
  "rustomjee-seasons": { village: "Bandra", cts: "629/1", rrZone: "Bandra East 22/104", scheme: "MHADA", society: "Seasons CHS Ltd", noc: "issued", dcpr: { zone: "Suburbs", plotAreaSqm: 14_200, roadWidthM: 18, fsiConsumed: 2.98, premiumFsi: 0.5, tdrLoaded: 0 }, approvals: ok(2021), rera: "completed", validUntil: "2021-06-30", carpet: 118 },
  "rustomjee-paramount": { village: "Bandra", cts: "E/721", rrZone: "Khar West 20/96", society: "Paramount CHS Ltd", noc: "pending", dcpr: { zone: "Suburbs", plotAreaSqm: 2_300, roadWidthM: 12, fsiConsumed: 1.2, premiumFsi: 0.5, tdrLoaded: 0 }, approvals: uc(2024), rera: "registered", validUntil: "2027-12-31", carpet: 128 },
  "prestige-ocean-towers": { village: "Bhuleshwar Division", cts: "1A/312", rrZone: "Marine Lines 2/7", scheme: "SRA", noc: "not_applicable", dcpr: { zone: "Island City", plotAreaSqm: 6_100, roadWidthM: 24, fsiConsumed: 3.2, premiumFsi: 0.5, tdrLoaded: 0 }, approvals: uc(2024), rera: "registered", validUntil: "2028-09-30", carpet: 140 },
  "prestige-jasdan-classic": { village: "Tardeo Division", cts: "1/711", rrZone: "Mahalaxmi 6/27", noc: "not_applicable", dcpr: { zone: "Island City", plotAreaSqm: 12_800, roadWidthM: 27, fsiConsumed: 2.6, premiumFsi: 0.5, tdrLoaded: 0 }, approvals: uc(2022), rera: "extended", validUntil: "2027-12-31", carpet: 128 },
  "hiranandani-gardens": { village: "Tirandaz", cts: "28A/4", rrZone: "Powai 113/534", society: "Glen Gate CHS Ltd", noc: "issued", dcpr: { zone: "Suburbs", plotAreaSqm: 18_900, roadWidthM: 24, fsiConsumed: 2.48, premiumFsi: 0.5, tdrLoaded: 0.35 }, approvals: ok(2018), rera: "completed", validUntil: "2018-12-31", carpet: 106 },
  "hiranandani-castle-rock": { village: "Tirandaz", cts: "28B/1", rrZone: "Powai 113/534", noc: "not_applicable", dcpr: { zone: "Suburbs", plotAreaSqm: 9_400, roadWidthM: 18, fsiConsumed: 2.1, premiumFsi: 0.5, tdrLoaded: 0.4 }, approvals: uc(2020), rera: "extended", validUntil: "2026-12-31", carpet: 114 },
};

export const GOA: Record<string, Goa> = {
  "sun-assagao-villas": { taluka: "Bardez", village: "Assagao", survey: "112", sub: "3", landUse: "settlement", rp: "Settlement S2", crz: "none", mundkar: "settled", conversion: "sanad_obtained", rera: "completed", validUntil: "2023-06-30", carpet: 240, history: [{ year: 1938, event: "Escritura of sale, Fernandes family", document: "Escritura de compra e venda" }, { year: 1994, event: "Inventory proceedings, heirs of João Fernandes", document: "Inventário 112/1994" }, { year: 2019, event: "Sale to Sun Estates Developers", document: "Sale deed, Mapusa Sub-Registrar" }] },
  "sun-aldona-reserve": { taluka: "Bardez", village: "Aldona", survey: "48", sub: "1", landUse: "settlement", rp: "Settlement S3", crz: "CRZ-III", mundkar: "none", conversion: "sanad_obtained", rera: "registered", validUntil: "2027-12-31", carpet: 210, history: [{ year: 1951, event: "Escritura, Pereira estate", document: "Escritura de partilha" }, { year: 2022, event: "Joint development agreement", document: "JDA, Mapusa Sub-Registrar" }] },
  "acron-waterfront": { taluka: "Bardez", village: "Porvorim", survey: "203", sub: "7", landUse: "settlement", rp: "Settlement S1", crz: "CRZ-II", mundkar: "none", conversion: "sanad_obtained", rera: "completed", validUntil: "2021-09-30", carpet: 64, history: [{ year: 1962, event: "Grant after Liberation, land survey", document: "Survey record 1971" }, { year: 2015, event: "Sale to Acron Developers", document: "Sale deed, Porvorim Sub-Registrar" }] },
  "acron-siolim-hills": { taluka: "Bardez", village: "Siolim", survey: "77", sub: "2", landUse: "orchard", rp: "Orchard (part) and Settlement S3", crz: "none", mundkar: "claimed", conversion: "applied", conversionDays: 240, rera: "registered", validUntil: "2027-03-31", carpet: 190, history: [{ year: 1947, event: "Escritura, Souza family", document: "Escritura de doação" }, { year: 2021, event: "Sale to Acron Developers", document: "Sale deed, Mapusa Sub-Registrar" }] },
  "acron-panjim-heights": { taluka: "Tiswadi", village: "Panaji", survey: "51", sub: "4", landUse: "settlement", rp: "Panaji ODP, residential", crz: "none", mundkar: "none", conversion: "not_required", rera: "completed", validUntil: "2019-12-31", carpet: 72, history: [{ year: 1965, event: "Municipal plot allotment", document: "CCP allotment" }, { year: 2014, event: "Sale to Acron Developers", document: "Sale deed, Ilhas Sub-Registrar" }] },
  "veera-strand": { taluka: "Bardez", village: "Candolim", survey: "164", sub: "9", landUse: "settlement", rp: "Settlement S2", crz: "CRZ-II", comunidade: "Candolim", mundkar: "none", conversion: "sanad_obtained", rera: "completed", validUntil: "2017-12-31", carpet: 68, history: [{ year: 1958, event: "Aforamento by the Comunidade de Candolim", document: "Escritura de aforamento" }, { year: 2012, event: "Transfer of aforamento rights to Veera Group with Comunidade consent", document: "Deed of transfer, Mapusa Sub-Registrar" }] },
  "veera-vagator-cove": { taluka: "Bardez", village: "Vagator", survey: "31", sub: "5", landUse: "settlement", rp: "Settlement S3", crz: "CRZ-III", mundkar: "none", conversion: "applied", conversionDays: 180, rera: "registered", validUntil: "2029-03-31", carpet: 260, history: [{ year: 1939, event: "Escritura of sale, Lobo family", document: "Escritura de compra e venda" }, { year: 2025, event: "Agreement to sell to Veera Group, subject to conversion", document: "Agreement for sale" }] },
  "veera-moira-gardens": { taluka: "Bardez", village: "Moira", survey: "88", sub: "6", landUse: "settlement", rp: "Settlement S3", crz: "none", mundkar: "none", conversion: "sanad_obtained", rera: "completed", validUntil: "2022-12-31", carpet: 70, history: [{ year: 1955, event: "Escritura, D'Mello family", document: "Escritura de partilha" }, { year: 2018, event: "Sale to Veera Group", document: "Sale deed, Mapusa Sub-Registrar" }] },
  "empire-benaulim": { taluka: "Salcete", village: "Benaulim", survey: "142", sub: "11", landUse: "settlement", rp: "Settlement S2", crz: "CRZ-III", mundkar: "claimed", conversion: "sanad_obtained", rera: "extended", validUntil: "2027-06-30", carpet: 74, history: [{ year: 1949, event: "Escritura, Colaço estate", document: "Escritura de compra e venda" }, { year: 2020, event: "Sale to Empire Realty", document: "Sale deed, Margao Sub-Registrar" }] },
  "empire-margao-central": { taluka: "Salcete", village: "Margao", survey: "19", sub: "2", landUse: "commercial", rp: "Margao ODP, commercial C2", crz: "none", mundkar: "none", conversion: "not_required", rera: "completed", validUntil: "2020-12-31", carpet: 66, history: [{ year: 1968, event: "Municipal plot", document: "Margao Municipal Council record" }, { year: 2016, event: "Sale to Empire Realty", document: "Sale deed, Margao Sub-Registrar" }] },
  "empire-colva-palms": { taluka: "Salcete", village: "Colva", survey: "56", sub: "3", landUse: "settlement", rp: "Settlement S2", crz: "none", mundkar: "settled", conversion: "sanad_obtained", rera: "completed", validUntil: "2018-12-31", carpet: 180, history: [{ year: 1952, event: "Escritura, Fernandes family", document: "Escritura de compra e venda" }, { year: 2014, event: "Mundkar purchase of dwelling plot settled", document: "Mamlatdar order, Salcete" }, { year: 2015, event: "Sale to Empire Realty", document: "Sale deed, Margao Sub-Registrar" }] },
  "sun-anjuna-retreat": { taluka: "Bardez", village: "Anjuna", survey: "212", sub: "1", landUse: "settlement", rp: "Settlement S2", crz: "none", comunidade: "Anjuna", mundkar: "none", conversion: "sanad_obtained", rera: "completed", validUntil: "2020-12-31", carpet: 220, history: [{ year: 1971, event: "Aforamento by the Comunidade de Anjuna", document: "Escritura de aforamento" }, { year: 2016, event: "Conversion sanad to settlement use", document: "Collector's sanad, North Goa" }, { year: 2017, event: "Transfer of aforamento rights to Sun Estates", document: "Deed of transfer, Mapusa Sub-Registrar" }] },
};

type Complaint = { dev: string; prop?: string; authority: "MahaRERA" | "Goa RERA"; n: string; filed: string; category: (typeof s.reraComplaints.$inferInsert)["category"]; status: (typeof s.reraComplaints.$inferInsert)["status"]; relief: string; outcome?: string; amount?: number };

export const COMPLAINTS: Complaint[] = [
  { dev: "lodha", prop: "lodha-park", authority: "MahaRERA", n: "CC006000000171245", filed: "2023-04-11", category: "Delayed possession", status: "order_passed", relief: "Interest on delayed possession of a Tower 4 unit", outcome: "Interest at SBI MCLR plus 2% ordered from the agreed date to possession", amount: 1_840_000 },
  { dev: "lodha", authority: "MahaRERA", n: "CC006000000198812", filed: "2024-08-02", category: "Carpet area", status: "hearing", relief: "Refund of consideration for 4.2 sq m carpet area shortfall" },
  { dev: "lodha", prop: "lodha-malabar", authority: "MahaRERA", n: "CC006000000221090", filed: "2026-01-19", category: "Amenities", status: "pending", relief: "Specification change to lobby finishes" },
  { dev: "oberoi", prop: "oberoi-sky-city", authority: "MahaRERA", n: "CC006000000187420", filed: "2023-11-08", category: "Quality", status: "disposed", relief: "Water seepage in two units", outcome: "Rectified by the promoter; complaint disposed" },
  { dev: "oberoi", authority: "MahaRERA", n: "CC006000000205531", filed: "2025-03-14", category: "Interest on delay", status: "withdrawn", relief: "Interest for a 3-month delay", outcome: "Withdrawn after settlement" },
  { dev: "rustomjee", prop: "rustomjee-paramount", authority: "MahaRERA", n: "CC006000000214477", filed: "2025-09-30", category: "Delayed possession", status: "pending", relief: "Rent for rehabilitated members during delayed redevelopment" },
  { dev: "rustomjee", prop: "rustomjee-seasons", authority: "MahaRERA", n: "CC006000000176302", filed: "2023-06-21", category: "Title", status: "disposed", relief: "Conveyance to the society", outcome: "Conveyance executed in 2024" },
  { dev: "prestige", prop: "prestige-jasdan-classic", authority: "MahaRERA", n: "CC006000000219006", filed: "2025-12-03", category: "Delayed possession", status: "hearing", relief: "Interest after the registration extension under s.6" },
  { dev: "hiranandani", prop: "hiranandani-castle-rock", authority: "MahaRERA", n: "CC006000000181913", filed: "2023-08-17", category: "Delayed possession", status: "order_passed", relief: "Interest for 22-month delay", outcome: "Interest ordered; promoter appealed to the Appellate Tribunal", amount: 2_960_000 },
  { dev: "hiranandani", prop: "hiranandani-castle-rock", authority: "MahaRERA", n: "CC006000000203345", filed: "2024-12-09", category: "Refund", status: "order_passed", relief: "Refund with interest after withdrawal", outcome: "Refund of ₹1.62 crore with interest ordered", amount: 16_200_000 },
  { dev: "hiranandani", authority: "MahaRERA", n: "CC006000000209874", filed: "2025-05-26", category: "Interest on delay", status: "pending", relief: "Interest for delayed possession, Thane phase" },
  { dev: "hiranandani", authority: "MahaRERA", n: "CC006000000216128", filed: "2025-10-14", category: "Amenities", status: "hearing", relief: "Clubhouse not handed over to the federation" },
  { dev: "sun-estates", prop: "sun-assagao-villas", authority: "Goa RERA", n: "GRERA/CMP/2023/041", filed: "2023-10-02", category: "Carpet area", status: "disposed", relief: "Shortfall in villa carpet area", outcome: "Compensation of ₹6.2 lakh paid", amount: 620_000 },
  { dev: "sun-estates", authority: "Goa RERA", n: "GRERA/CMP/2025/017", filed: "2025-04-18", category: "Carpet area", status: "pending", relief: "Pool deck counted in carpet area" },
  { dev: "acron", prop: "acron-siolim-hills", authority: "Goa RERA", n: "GRERA/CMP/2025/033", filed: "2025-07-22", category: "Delayed possession", status: "hearing", relief: "Delay attributed to conversion of the orchard portion" },
  { dev: "acron", prop: "acron-waterfront", authority: "Goa RERA", n: "GRERA/CMP/2022/012", filed: "2022-03-09", category: "Amenities", status: "disposed", relief: "Rental pool statements", outcome: "Promoter to issue audited rental pool statements quarterly" },
  { dev: "veera", prop: "veera-strand", authority: "Goa RERA", n: "GRERA/CMP/2021/008", filed: "2021-05-11", category: "Title", status: "order_passed", relief: "Title to the Comunidade wing", outcome: "Promoter directed to produce Comunidade consent; produced in 2022" },
  { dev: "veera", prop: "veera-vagator-cove", authority: "Goa RERA", n: "GRERA/CMP/2026/004", filed: "2026-02-10", category: "Refund", status: "pending", relief: "Refund of booking amount pending conversion" },
  { dev: "empire", prop: "empire-benaulim", authority: "Goa RERA", n: "GRERA/CMP/2024/021", filed: "2024-06-04", category: "Delayed possession", status: "order_passed", relief: "Interest for delay", outcome: "Interest ordered from June 2024", amount: 1_120_000 },
  { dev: "empire", prop: "empire-benaulim", authority: "Goa RERA", n: "GRERA/CMP/2025/029", filed: "2025-06-30", category: "Delayed possession", status: "hearing", relief: "Second delay after revised completion date" },
  { dev: "empire", prop: "empire-benaulim", authority: "Goa RERA", n: "GRERA/CMP/2025/041", filed: "2025-11-12", category: "Refund", status: "pending", relief: "Refund with interest" },
  { dev: "empire", authority: "Goa RERA", n: "GRERA/CMP/2025/044", filed: "2025-12-01", category: "Interest on delay", status: "pending", relief: "Escrow shortfall complaint" },
];

/** Sample land records attached to selected properties: one of each kind, plus two flagged cases. */
const LAND: { slug: string; kind: LandRecordKind; text: string }[] = [
  { slug: "oberoi-sky-city", kind: "7_12", text: sample712({ district: "Mumbai Suburban", taluka: "Borivali", village: "Magathane", survey: "२१२", hissa: "1", area: "10.10.00", holders: "Oberoi Realty Limited", other: "नाही (Nil)", mutation: "4521, 4876, 5102", classNo: 1 }) },
  { slug: "rustomjee-elements", kind: "property_card", text: samplePropertyCard({ division: "K-West", village: "Juhu", cts: "1123/A", sheet: "14", area: "21,400", tenure: "A (freehold)", holder: "Rustomjee Elements CHS Ltd", entries: ["12/03/2015 Conveyance deed in favour of Keystone Realtors Ltd", "18/09/2023 Deemed conveyance in favour of Rustomjee Elements CHS Ltd"] }) },
  { slug: "rustomjee-paramount", kind: "property_card", text: samplePropertyCard({ division: "H-West", village: "Bandra", cts: "E/721", sheet: "41", area: "2,300", tenure: "C (Collector's lease)", holder: "Paramount Co-operative Housing Society Ltd", entries: ["04/06/1972 Lease deed from the Collector of Mumbai Suburban District", "22/02/2024 Development agreement in favour of Keystone Realtors Ltd", "14/03/2024 Mortgage to HDFC Capital Advisors Ltd"] }) },
  { slug: "hiranandani-castle-rock", kind: "7_12", text: sample712({ district: "Mumbai Suburban", taluka: "Kurla", village: "Tirandaz", survey: "२८", hissa: "B/1", area: "0.94.00", holders: "Hiranandani Developers Pvt Ltd", other: "बोजा: Construction finance charge, ICICI Bank Ltd, Rs. 310,00,00,000", mutation: "1872, 2214", classNo: 1 }) },
  { slug: "sun-assagao-villas", kind: "form_i_xiv", text: sampleFormI({ taluka: "Bardez", village: "Assagao", survey: "112", sub: "3", field: "Bhatt", area: "4,320", landClass: "Settlement", occupants: "Sun Estates Developers", tenant: "Nil", mundkar: "Nil", other: "Nil", crop: "Uncultivable", mutation: "2210" }) },
  { slug: "acron-siolim-hills", kind: "form_i_xiv", text: sampleFormI({ taluka: "Bardez", village: "Siolim", survey: "77", sub: "2", field: "Morod", area: "11,800", landClass: "Orchard (cashew)", occupants: "Acron Developers", tenant: "Nil", mundkar: "Anant Naik", other: "Nil", crop: "Cashew", mutation: "1931" }) },
  { slug: "empire-benaulim", kind: "form_i_xiv", text: sampleFormI({ taluka: "Salcete", village: "Benaulim", survey: "142", sub: "11", field: "Dongor", area: "6,400", landClass: "Settlement", occupants: "Empire Realty Goa", tenant: "Nil", mundkar: "Rosario Dias (claim pending)", other: "Mamlatdar case MUN/SAL/14/2024", crop: "Uncultivable", mutation: "3302" }) },
  { slug: "sun-anjuna-retreat", kind: "escritura", text: sampleComunidade({ comunidade: "Anjuna", aforamento: "AF-1187", plot: "41", foreiro: "Francis D'Souza", foro: "1,200", area: "2,640", gb: "14/02/1971", admin: "approved 02/05/1971", escritura: "18/06/1971", notary: "Notário de Mapusa", condition: "residential use, foro payable annually to the Comunidade" }) },
  { slug: "veera-strand", kind: "escritura", text: sampleComunidade({ comunidade: "Candolim", aforamento: "AF-0612", plot: "17", foreiro: "Caetano Lobo", foro: "800", area: "3,100", gb: "09/11/1958", admin: "approved 21/01/1959", escritura: "03/03/1959", notary: "Notário de Bardez", condition: "not to alienate without consent of the Comunidade" }) },
];

export async function seedIndia(db: DB, tenantId: string, id: (k: string) => string) {
  const propId = (slug: string) => id(`prop:${slug}`);
  const devId = (k: string) => id(`dev:${k}`);
  const bySlug = (slug: string) => PROPERTIES.find((p) => p.slug === slug)!;

  const rows: (typeof s.indiaPropertyRecords.$inferInsert)[] = [];
  for (const [slug, m] of Object.entries(MUMBAI)) {
    const p = bySlug(slug);
    const rr = READY_RECKONER.find((z) => z.zone === m.rrZone)!;
    rows.push({ id: id(`india:${slug}`), tenantId, propertyId: propId(slug), state: "MH", district: /Division$/.test(m.village) ? "Mumbai City" : "Mumbai Suburban", village: m.village, reraAuthority: "MahaRERA", reraNumber: p.rera.replace("MahaRERA ", ""), reraStatus: m.rera, reraValidUntil: m.validUntil, ctsNumber: m.cts, readyReckonerRate: rr.residentialPerSqm, readyReckonerZone: m.rrZone, readyReckonerYear: READY_RECKONER_YEAR, carpetAreaSqm: m.carpet, societyName: m.society ?? null, societyNocStatus: m.noc ?? null, mcgmApprovals: m.approvals, redevelopmentScheme: m.scheme ?? null, dcpr: m.dcpr, titleHistory: [] });
  }
  for (const [slug, g] of Object.entries(GOA)) {
    const p = bySlug(slug);
    rows.push({ id: id(`india:${slug}`), tenantId, propertyId: propId(slug), state: "GA", district: g.taluka === "Salcete" ? "South Goa" : "North Goa", village: g.village, reraAuthority: "Goa RERA", reraNumber: p.rera, reraStatus: g.rera, reraValidUntil: g.validUntil, surveyNumber: g.survey, subDivision: g.sub, readyReckonerRate: GOA_MINIMUM_VALUE[g.village] ?? null, readyReckonerZone: `${g.village} (Collector's minimum value)`, readyReckonerYear: READY_RECKONER_YEAR, carpetAreaSqm: g.carpet, landUse: g.landUse, rp2021Zone: g.rp, crzZone: g.crz, comunidade: Boolean(g.comunidade), comunidadeName: g.comunidade ?? null, mundkarStatus: g.mundkar, conversionStatus: g.conversion, conversionDays: g.conversionDays ?? null, titleHistory: g.history });
  }
  await db.insert(s.indiaPropertyRecords).values(rows).onConflictDoNothing();

  await db
    .insert(s.reraComplaints)
    .values(COMPLAINTS.map((c) => ({ id: id(`rera:${c.n}`), tenantId, developerId: devId(c.dev), propertyId: c.prop ? propId(c.prop) : null, authority: c.authority, complaintNumber: c.n, filedOn: c.filed, category: c.category, status: c.status, reliefSought: c.relief, outcome: c.outcome ?? null, amountInr: c.amount ?? null })))
    .onConflictDoNothing();

  const LABEL: Record<LandRecordKind, string> = { "7_12": "7/12 extract", property_card: "Property card", form_i_xiv: "Form I and XIV", escritura: "Aforamento and Escritura" };
  for (const l of LAND) {
    const parsed = parseLandRecord(l.text, l.kind)!;
    const docId = id(`doc:land:${l.slug}:${l.kind}`);
    await db.insert(s.documents).values({ id: docId, tenantId, propertyId: propId(l.slug), title: `${LABEL[l.kind]}: ${bySlug(l.slug).name}`, type: "land_record", pages: 1, sizeBytes: l.text.length, contentText: l.text, extractedData: parsed.parsed, embedding: embed(l.text) }).onConflictDoNothing();
    await db.insert(s.landRecords).values({ id: id(`land:${l.slug}:${l.kind}`), tenantId, propertyId: propId(l.slug), documentId: docId, recordType: l.kind, parsed: parsed.parsed as unknown as Record<string, unknown>, confidence: parsed.confidence, parser: "text", warnings: parsed.warnings, sourceText: l.text, embedding: embed(l.text) }).onConflictDoNothing();
  }
}
