import {
  Zap,
  FileSignature,
  MessageCircle,
  Globe,
  HeartPulse,
  ArrowRightLeft,
  Activity,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Coins,
  CreditCard,
  Database,
  FileCheck,
  FileSpreadsheet,
  FileText,
  Flag,
  FolderOpen,
  Gauge,
  GitBranch,
  Globe2,
  Handshake,
  Inbox,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LineChart,
  ListChecks,
  type LucideIcon,
  MapPin,
  Megaphone,
  MessageSquare,
  Network,
  Palette,
  PieChart,
  Plug,
  Receipt,
  ScrollText,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  SquareStack,
  Target,
  UserCog,
  Users,
  Workflow,
} from "lucide-react";

export type Area = "analyst" | "client" | "admin" | "platform";

export interface NavItem {
  href: string;
  label: string;
  /** Single-key "g then …" shortcut. */
  key?: string;
  /** Hidden when the tenant has switched this feature off. */
  feature?: "assistant" | "clientPortal" | "marketTiming" | "crossBorder";
}

export interface NavSection {
  title?: string;
  items: NavItem[];
}

/** Navigation is set in type alone. No icons: every label is already clear. */
export const NAV: Record<Area, NavSection[]> = {
  analyst: [
    {
      items: [
        { href: "/analyst/dashboard", label: "Dashboard", key: "d" },
        { href: "/analyst/insights", label: "Insights", key: "i" },
        { href: "/analyst/mandates", label: "Mandates", key: "m" },
        { href: "/analyst/deals", label: "Deals", key: "e" },
        { href: "/analyst/commissions", label: "My commissions" },
        { href: "/analyst/memos", label: "Memos", key: "o" },
        { href: "/analyst/clients", label: "Clients", key: "c" },
      ],
    },
    {
      title: "Brokerage",
      items: [
        { href: "/analyst/leads", label: "Leads", key: "l" },
        { href: "/analyst/listings", label: "Listings", key: "t" },
        { href: "/analyst/marketing", label: "Marketing" },
        { href: "/analyst/rentals", label: "Rentals", key: "r" },
        { href: "/analyst/referrals", label: "Referrals" },
      ],
    },
    {
      title: "Research",
      items: [
        { href: "/analyst/properties", label: "Properties", key: "p" },
        { href: "/analyst/developers", label: "Developers", key: "v" },
        { href: "/analyst/market", label: "Market", key: "k" },
        { href: "/analyst/federation", label: "Federation", key: "f" },
        { href: "/analyst/benchmarks", label: "Benchmarks", key: "b" },
        { href: "/analyst/ai-memory", label: "AI memory" },
        { href: "/analyst/assistant", label: "Assistant", key: "a", feature: "assistant" },
      ],
    },
    {
      title: "India",
      items: [
        { href: "/analyst/india", label: "Overview" },
        { href: "/analyst/india/mumbai", label: "Mumbai" },
        { href: "/analyst/india/goa", label: "Goa" },
        { href: "/analyst/india/tax-calculator", label: "Tax calculator" },
      ],
    },
    {
      title: "Account",
      items: [
        { href: "/notifications", label: "Notifications", key: "n" },
        { href: "/analyst/settings", label: "Settings", key: "s" },
      ],
    },
  ],
  client: [
    {
      items: [
        { href: "/client/portfolio", label: "Portfolio", key: "p" },
        { href: "/client/deals", label: "Transactions", key: "t" },
        { href: "/client/insights", label: "Insights", key: "i" },
        { href: "/client/market-insights", label: "Market insights" },
        { href: "/client/opportunities", label: "Opportunities", key: "o" },
        { href: "/client/recommendations", label: "Recommendations", key: "r" },
      ],
    },
    {
      title: "Reporting",
      items: [
        { href: "/client/reports", label: "Reports" },
        { href: "/client/statements", label: "Statements" },
        { href: "/client/goals", label: "Goals", key: "g" },
        { href: "/client/private-banking", label: "Private banking" },
      ],
    },
    {
      title: "Workspace",
      items: [
        { href: "/client/documents", label: "Documents", key: "d" },
        { href: "/client/kyc", label: "Identity verification" },
        { href: "/client/contracts", label: "Contracts" },
        { href: "/client/invoices", label: "Invoices" },
        { href: "/client/tax-documents", label: "Tax documents" },
        { href: "/client/india", label: "India" },
        { href: "/client/nri", label: "NRI plan" },
        { href: "/client/messages", label: "Messages", key: "m" },
        { href: "/notifications", label: "Notifications", key: "n" },
        { href: "/client/assistant", label: "Assistant", key: "a", feature: "assistant" },
        { href: "/client/settings", label: "Settings", key: "s" },
      ],
    },
  ],
  admin: [
    {
      items: [
        { href: "/admin/dashboard", label: "Overview", key: "o" },
        { href: "/admin/users", label: "Users", key: "u" },
        { href: "/admin/branding", label: "Branding", key: "b" },
        { href: "/admin/billing", label: "Billing", key: "i" },
        { href: "/admin/team", label: "Team and offices", key: "m" },
      ],
    },
    {
      title: "Operations",
      items: [
        { href: "/admin/migrate", label: "Data migration", key: "g" },
        { href: "/admin/portals", label: "Portals", key: "e" },
        { href: "/admin/website", label: "Website", key: "w" },
        { href: "/admin/whatsapp", label: "WhatsApp", key: "j" },
        { href: "/admin/lead-response", label: "Lead response", key: "q" },
      ],
    },
    {
      title: "Revenue",
      items: [
        { href: "/admin/commissions", label: "Commissions", key: "c" },
        { href: "/admin/commission-structures", label: "Commission structures", key: "z" },
        { href: "/admin/contracts/templates", label: "Contract templates" },
        { href: "/admin/invoices", label: "Invoices", key: "v" },
      ],
    },
    {
      title: "Clients",
      items: [
        { href: "/admin/kyc", label: "KYC and AML", key: "k" },
        { href: "/admin/reports", label: "Reports", key: "r" },
        { href: "/admin/data-products", label: "Data products", key: "p" },
      ],
    },
    {
      title: "Governance",
      items: [
        { href: "/admin/compliance", label: "Compliance", key: "y" },
        { href: "/admin/automations", label: "Automations", key: "a" },
        { href: "/admin/ai-control", label: "AI control", key: "x" },
        { href: "/admin/audit", label: "Audit log", key: "l" },
        { href: "/admin/health", label: "System health", key: "h" },
        { href: "/admin/insights-config", label: "Intelligence", key: "t" },
        { href: "/admin/integrations", label: "Integrations", key: "n" },
        { href: "/admin/seed", label: "Demonstration data", key: "s" },
      ],
    },
  ],
  platform: [
    {
      items: [
        { href: "/platform/dashboard", label: "Dashboard", key: "d" },
        { href: "/platform/tenants", label: "Tenants", key: "t" },
        { href: "/platform/metrics", label: "Metrics", key: "m" },
        { href: "/platform/federation", label: "Federation", key: "f" },
        { href: "/platform/health", label: "System health", key: "h" },
        { href: "/platform/federation/dashboard", label: "Federation dashboard" },
        { href: "/platform/bi", label: "Business intelligence", key: "b" },
        { href: "/platform/agents", label: "Agents", key: "a" },
      ],
    },
  ],
};

export const SEGMENT_LABEL: Record<string, string> = {
  analyst: "Analyst",
  client: "Client",
  admin: "Admin",
  dashboard: "Dashboard",
  mandates: "Mandates",
  new: "Create mandate",
  memos: "Memos",
  clients: "Clients",
  properties: "Properties",
  developers: "Developers",
  market: "Market",
  assistant: "Assistant",
  settings: "Settings",
  portfolio: "Portfolio",
  opportunities: "Opportunities",
  recommendations: "Recommendations",
  documents: "Documents",
  messages: "Messages",
  users: "Users",
  integrations: "Integrations",
  audit: "Audit log",
  seed: "Demonstration data",
  branding: "Branding",
  billing: "Billing",
  platform: "Platform",
  tenants: "Tenants",
  metrics: "Metrics",
  insights: "Insights",
  federation: "Federation",
  "insights-config": "Intelligence",
  india: "India",
  mumbai: "Mumbai",
  goa: "Goa",
  "tax-calculator": "Tax calculator",
  records: "Property file",
  nri: "NRI plan",
  deals: "Deals",
  commissions: "Commissions",
  structures: "Structures",
  invoices: "Invoices",
  kyc: "KYC",
  reports: "Reports",
  statements: "Statements",
  goals: "Goals",
  "tax-documents": "Tax documents",
  "private-banking": "Private banking",
  benchmarks: "Benchmarks",
  bi: "Business intelligence",
  "data-products": "Data products",
  "market-insights": "Market insights",
  compliance: "Compliance",
  automations: "Automations",
  "ai-control": "AI control",
  "ai-memory": "AI memory",
  agents: "Agents",
  notifications: "Notifications",
  journey: "Journey",
  leads: "Leads",
  listings: "Listings",
  marketing: "Marketing",
  rentals: "Rentals",
  referrals: "Referrals",
  team: "Team and offices",
};

/** 16px line icons at 1.5px stroke, one per destination. */
export const NAV_ICON: Record<string, LucideIcon> = {
  "/analyst/dashboard": LayoutDashboard,
  "/analyst/insights": Sparkles,
  "/analyst/mandates": Briefcase,
  "/analyst/deals": Handshake,
  "/analyst/commissions": Coins,
  "/analyst/memos": FileText,
  "/analyst/clients": Users,
  "/analyst/leads": Inbox,
  "/analyst/listings": SquareStack,
  "/analyst/marketing": Megaphone,
  "/analyst/rentals": KeyRound,
  "/analyst/referrals": GitBranch,
  "/admin/team": UserCog,
  "/admin/migrate": ArrowRightLeft,
  "/admin/health": HeartPulse,
  "/admin/portals": Megaphone,
  "/admin/website": Globe,
  "/admin/whatsapp": MessageCircle,
  "/admin/lead-response": Zap,
  "/admin/commission-structures": Calculator,
  "/client/kyc": ShieldCheck,
  "/client/contracts": FileSignature,
  "/admin/contracts/templates": FileSignature,
  "/platform/health": HeartPulse,
  "/analyst/properties": Building2,
  "/analyst/developers": Building,
  "/analyst/market": LineChart,
  "/analyst/federation": Network,
  "/analyst/benchmarks": BarChart3,
  "/analyst/ai-memory": Brain,
  "/analyst/assistant": Bot,
  "/analyst/india": Globe2,
  "/analyst/india/mumbai": MapPin,
  "/analyst/india/goa": MapPin,
  "/analyst/india/tax-calculator": Calculator,
  "/notifications": Bell,
  "/analyst/settings": Settings,
  "/client/portfolio": PieChart,
  "/client/deals": Handshake,
  "/client/insights": Sparkles,
  "/client/market-insights": LineChart,
  "/client/opportunities": Target,
  "/client/recommendations": ListChecks,
  "/client/reports": BookOpen,
  "/client/statements": FileSpreadsheet,
  "/client/goals": Flag,
  "/client/private-banking": Landmark,
  "/client/documents": FolderOpen,
  "/client/invoices": Receipt,
  "/client/tax-documents": FileCheck,
  "/client/india": Globe2,
  "/client/nri": Globe2,
  "/client/messages": MessageSquare,
  "/client/assistant": Bot,
  "/client/settings": Settings,
  "/admin/dashboard": LayoutDashboard,
  "/admin/users": Users,
  "/admin/branding": Palette,
  "/admin/billing": CreditCard,
  "/admin/commissions": Coins,
  "/admin/invoices": Receipt,
  "/admin/kyc": ShieldCheck,
  "/admin/reports": BookOpen,
  "/admin/data-products": SquareStack,
  "/admin/compliance": Shield,
  "/admin/automations": Workflow,
  "/admin/ai-control": Gauge,
  "/admin/audit": ScrollText,
  "/admin/insights-config": Sparkles,
  "/admin/integrations": Plug,
  "/admin/seed": Database,
  "/platform/dashboard": LayoutDashboard,
  "/platform/tenants": Building2,
  "/platform/metrics": Activity,
  "/platform/federation": Network,
  "/platform/federation/dashboard": GitBranch,
  "/platform/bi": BarChart3,
  "/platform/agents": Bot,
};
export const FALLBACK_ICON: LucideIcon = Inbox;

export const AREA_LABEL: Record<Area, string> = { analyst: "Analyst desk", client: "Client portal", admin: "Administration", platform: "Nakhla platform" };

export function navFor(area: Area, features?: Partial<Record<NonNullable<NavItem["feature"]>, boolean>>): NavSection[] {
  return NAV[area].map((s) => ({ ...s, items: s.items.filter((i) => !i.feature || features?.[i.feature] !== false) }));
}
